Retorna a dados da produção de uvas, vinhos e derivados
---
parameters:
  - in: path
    name: ano
    type: integer
    required: true

responses:
  200:
    description: Dados de produção do ano enviado
  401:
    description: Ano inválido
