Retorna a dados da produção de uvas, vinhos e derivados a partir de 1970.
---
parameters:
  - in: path
    name: ano
    type: integer
    required: true
  - in: header
    name: authorization    # <---- HTTP header name
    required: true
    type: string
    description: Adicione o termo Bearer antes do token
security:
  - Bearer: []

responses:
  200:
    description: Dados de produção do ano enviado
  226:
    description: Dados enviados do cache local
  400:
    description: Ano inválido
  503:
    description: Serviço indisponível, tente mais tarde
